Guitar/Models/MusicScore.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guitar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicScore()
        {
            this.MusicScoreCollection = new HashSet<MusicScoreCollection>();
            this.MusicScoreComment = new HashSet<MusicScoreComment>();
            this.MusicScoreReply = new HashSet<MusicScoreReply>();
        }
    
        public int Ms_id { get; set; }
        public int User_id { get; set; }
        public string Ms_title { get; set; }
        public string Score { get; set; }
        public string Ms_img { get; set; }
        public string Ms_label { get; set; }
        public System.DateTime Ms_addtime { get; set; }
        public int ReadCount { get; set; }
        public int Collection { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreCollection> MusicScoreCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreComment> MusicScoreComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreReply> MusicScoreReply { get; set; }
    }
}

Guitar/Controllers/MusicScoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Guitar.Models;
using Guitar.ViewModel;
//using MvcPager;
using Webdiyer.WebControls.Mvc;
//using Guitar.Attributes;

namespace Guitar.Controllers
{
    public class MusicScoreController : Controller
    {
        private GuitarEntities db = new GuitarEntities();

        #region 吉他谱
        public ActionResult Index(int id = 1, int pageIndex = 1, int page = 1)
        {
            //var str1 = "古典吉他";
            var users = (from m in db.Users.OrderByDescending(p => p.User_addtime) select m).Take(6);

            var score1 = (from m in db.MusicScore.Where(p => p.Ms_label == "古典吉他").OrderByDescending(p => p.Ms_addtime) select m).Take(10);
            var score2 = (from m in db.MusicScore.Where(p => p.Ms_label == "民谣吉他").OrderByDescending(p => p.Ms_addtime) select m).Take(10);
            var score3 = (from m in db.MusicScore.Where(p => p.Ms_label == "电吉他").OrderByDescending(p => p.Ms_addtime) select m).Take(10);
            var score4 =( from m in db.MusicScore.Where(p => p.Ms_label == "尤克里里").OrderByDescending(p => p.Ms_addtime) select m).Take(10);
            var score5 = (from m in db.MusicScore.Where(p => p.Ms_label == "其他").OrderByDescending(p => p.Ms_addtime) select m).Take(10);
            var score6 = (from m in db.MusicScore.OrderByDescending(p => p.ReadCount) select m);
            const int pageSize = 20;
            if (Request.IsAjaxRequest())
            {
                var target = Request.QueryString["target"];
                if (target == "mscore")
                {
                    return PartialView("_Index1",score6.ToPagedList(id, pageSize));
                }
            }
          
            var index = new Guitar.ViewModel.MusicDetailsViewModel()
            {
                MScore1 = score1,
                MScore2 = score2,
                MScore3 = score3,
                MScore4 = score4,
                MScore5=score5,
                MScore6=score6.ToPagedList(page, pageSize),
                Us2 = users,
            };
            return View(index);
        }
        #endregion
        #region   点击量
        [HttpPost]
        public string AddClick(int MsId)
        {
            var ms = db.MusicScore.Find(MsId);
            var mscount= ms.ReadCount + 1;
            ms.ReadCount = ms.ReadCount + 1;
            db.SaveChanges();
            return mscount.ToString();
        }
        #endregion
        #region 发布乐谱
        // GET: MusicScores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MusicScores/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(MusicScore musicScore)
        {
            var sel1 = Request["sel"];
            var sel = sel1.Trim();
            HttpPostedFileBase postimageBase = Request.Files["Image1"];
            if (ModelState.IsValid)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        if (postimageBase != null)
                        {
                            string filePath = postimageBase.FileName;
                            string filename = filePath.Substring(filePath.LastIndexOf("\\") + 1);
                            string serverpath = Server.MapPath(@"/Images/FM/") + filename;
                            string relativepath = @"/Images/FM/" + filename;
                            postimageBase.SaveAs(serverpath);
                            musicScore.Ms_img = relativepath;
                        }
                        else
                        {
                            return Content("<script>;alert('请先上传封面！');history.go(-1)</script>");

                        }
                        musicScore.User_id = Convert.ToInt32(Session["Users_id"].ToString());
                        musicScore.Ms_addtime = System.DateTime.Now;
                        musicScore.Ms_label = sel;
                        db.MusicScore.Add(musicScore);
                        db.SaveChanges();
                        //return Content("<script>;alert('发布成功!');window.location.href='/Publish_Food/Index_PF'</script>");
                        return Content("<script>;alert('发布成功!');history.go(-1)</script>");
                    }
                    else
                    {
                        return Content("<script>;alert('发布失败！');history.go(-1)</script>");
                    }
                }
                catch (Exception ex)
                {
                    return Content(ex.Message);
                }
            }
            return View();
        }
        #endregion
        #region 删除乐谱
        // GET: MusicScore/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicScore musicScore = db.MusicScore.Find(id);
            if (musicScore == null)
            {
                return HttpNotFound();
            }
            return View(musicScore);
        }

        // POST: MusicScore/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MusicScore musicScore = db.MusicScore.Find(id);
            db.MusicScore.Remove(musicScore);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
        #region  乐谱展示
        public ActionResult Display(int? id, int md = 1, int pageIndex = 1, int page = 1)
        {
            //const int pageSize = 5;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TempData["Ms_idd"] = id;
            ViewBag.Msid= id;
            TempData["Ms_id2"] = id;
            MusicScore ms = db.MusicScore.Find(id);
            //MusicScoreStatistics msta = db.MusicScoreStatistics.Find(id);
            var usid = (from m in db.MusicScore.Where(p => p.Ms_id == id) select m.User_id).FirstOrDefault();
            Users us = db.Users.Find(usid);
            //MusicScoreStatistics msta = db.MusicScoreStatistics.Find(id);

            if (ms == null  && us == null)
            {
                return HttpNotFound();
            }

            //var us=from m in db.Users.Where(p=>p.User_id==usid) select m;
            var ms1 = (from m in db.MusicScore.Where(p => p.User_id == usid).OrderByDescending(p => p.Ms_addtime) select m).Take(5);
            var msc = from m in db.MusicScoreComment.Where(p => p.Ms_id == id).OrderByDescending(p => p.Addtime) select m;
            var comment = from m in db.MusicScoreComment
                          join n in db.Users on m.User_id equals n.User_id
                          select new MusicScoreCommentViewModel
                          {
                              Ms_commentid = m.Ms_commentid,
                              Ms_id = m.Ms_id,
                              content = m.content,
                              Addtime = m.Addtime,
                              User_id = n.User_id,
                              User_name = n.User_name,
                              User_img = n.User_img,
                          };
            //var comment1 = .ToPagedList(idd, pageSize);
            var msr = (from n in db.MusicScoreReply
                       join m in msc on n.Ms_commentid equals m.Ms_commentid
                       join q in db.Users on n.User_id equals q.User_id
                       select new MusicCommentReplyViewModel
                       {
                           Ms_replyid = n.Ms_replyid,
                           Ms_commentid = m.Ms_commentid,
                           content = n.content,
                           Addtime = n.Addtime,
                           Ms_id = m.Ms_id,
                           User_id = n.User_id,
                           User_name = q.User_name,
                           User_img = q.User_img
                       });
            int commentid = Convert.ToInt32(Request["Commentid1"]);
            var msrr = from m in db.MusicScoreReply.Where(p => p.Ms_commentid == commentid).OrderByDescending(p => p.Addtime) select m;
          
            var comment1 = from m in comment.Where(p => p.Ms_id == id).OrderByDescending(p => p.Addtime) select m;
            //var msta = from m in db.MusicScoreStatistics.Where(p => p.Ms_id == id) select m;
            //var msta = from m in db.MusicScoreStatistics where m.Ms_id == id select m;
            //分页数据
            const int pageSize = 5;
            if (Request.IsAjaxRequest())
            {
                var target = Request.QueryString["target"];
                if (target == "articles")
                {
                    return PartialView("_display1",comment1.ToPagedList(md, pageSize));
                }
            }
            var index = new Guitar.ViewModel.MusicDetailsViewModel()
            {
                Us = us,
                MScore = ms,
                MScore1 = ms1,
                MSC = msc,
                MSR = msr,
                Msr = msrr,
                msc11=comment1.ToPagedList(page, pageSize),
            };
            //if (Request.IsAjaxRequest())
            //    return PartialView("_PartialPage1", comment.OrderByDescending(a => a.Addtime).ToPagedList(md, 3));
            return View(index);
        }
        #endregion 

        #region 评论乐谱

Guitar/Views/MusicScore/Create.cshtml
@using MvcSiteMapProvider.Web.Html
@model Guitar.Models.MusicScore

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}
<script src="~/ueditor/ueditor.all.js"></script>
<script src="~/ueditor/ueditor.config.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="~/ueditor/themes/default/css/ueditor.css" rel="stylesheet" />
<script src="~/ueditor/lang/zh-cn/zh-cn.js"></script>
<link href="~/bootstrap-3.3.7-dist/css/bootstrap-fileinput.css" rel="stylesheet" />
<script src="~/bootstrap-3.3.7-dist/js/bootstrap-fileinput.js"></script>
<style>
    .fab {
        border-bottom: 2px solid #e8e8e8;
        color: #222;
        font-size: 16px;
        height: 64px;
        list-style: none;
    }

    .fabiao {
        display: inline-block;
        margin-right: 30px;
        line-height: 52px;
        cursor: pointer;
    }

        .fabiao a {
            text-decoration: none;
        }
</style>
<div>@Html.MvcSiteMap().SiteMapPath()</div>
<ul class="fab">
    <li class="fabiao"><a href="@Url.Action("Create","MusicScore")" style="color:#090909">发布吉他谱</a></li>
    <li class="fabiao"><a href="@Url.Action("Create","Video")">发表视频</a></li>
    <li class="fabiao"><a href="@Url.Action("Create","Posts")" >发表帖子</a></li>
</ul>
@using (Html.BeginForm("Create", "MusicScore", new { area = "" }, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="table-responsive" style="padding-top:15px;">
        <table class="table">
            <tbody>
                <tr>
                    <td colspan="3">
                        @Html.EditorFor(model => model.Ms_title, new { htmlAttributes = new { @class = "form-control", @placeholder = "歌曲名称(简单描述)" } })
                        @Html.ValidationMessageFor(model => model.Ms_title, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.TextAreaFor(model => model.Score, htmlAttributes: new { @id = "Score" })
                        @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <h4>选择封面</h4>
                    </td>
                    <td>
                        @*<input type="file" name="Image1" />*@
                        @*@Html.EditorFor(model => model.Ms_img, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Ms_img, "", new { @class = "text-danger" })*@
                        <div class="form-group" id="uploadForm" enctype='multipart/form-data'>
                            <div class="h4">图片预览</div>
                            <div class="fileinput fileinput-new" data-provides="fileinput" id="exampleInputUpload">
                                <div class="fileinput-new thumbnail" style="width: 200px;height: auto;max-height:150px;">
                                    <img id='picImg' style="width: 100%;height: auto;max-height: 140px;" src="images/noimage.png" alt="" />
                                </div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                <div>
                                    <span class="btn btn-primary btn-file">
                                        <span class="fileinput-new">选择文件</span>
                                        <span class="fileinput-exists">换一张</span>
                                        <input type="file" name="Image1" id="Image1" accept="image/gif,image/jpeg,image/x-png">
                                    </span>
                                    <a href="javascript:;" class="btn btn-warning fileinput-exists" data-dismiss="fileinput">移除</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><h4>选择标签</h4></td>
                    <td colspan="2">

                        <div class="btn-group btn-group-lg">
                            <button id="bu2" type="button" class="btn btn-default">古典吉他</button>
                        </div>
                        <div class="btn-group btn-group-lg">
                            <button id="bu3" type="button" class="btn btn-default">民谣吉他</button>
                        </div>
                        <div class="btn-group btn-group-lg">
                            <button id="bu4" type="button" class="btn btn-default">电吉他</button>
                        </div>
                        <div class="btn-group btn-group-lg">
                            <button id="bu5" type="button" class="btn btn-default">尤克里里</button>
                        </div>
                        <div class="btn-group btn-group-lg">
                            <button id="bu6" type="button" class="btn btn-default">其他</button>
                        </div>
                        <br />
                        <br />
                        <a style="color:black;text-decoration:none;">你的选择:</a><label for="lab" id="lab"></label><input type="hidden" name="sel" id="sel" />
                        <br />
                    </td>
                </tr>

                @*<div class="form-group">
                        @Html.LabelFor(model => model.Ms_description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Ms_description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Ms_description, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <tr>
                    <td colspan="3">
                        <input type="submit" value="发布" class="btn btn-info btn-lg" />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

<script>
    $(document).ready(function () {

        $("#bu2").click(function () {
            $("#lab").html("古典吉他");
            $("#sel").val("古典吉他");
            //$.post("/Posts/Create", { frontViewData: data }, function () {
            //    //alert("submit data is OK!");
            //});
            //location.href = "/home/getvalue?method=querystring";
        });
        $("#bu3").click(function () {
            $("#lab").html("民谣吉他");
            $("#sel").val("民谣吉他");
        });
        $("#bu4").click(function () {
            $("#lab").html("电吉他");
            $("#sel").val("电吉他");
        });
        $("#bu5").click(function () {
            $("#lab").html("尤克里里")
            $("#sel").val("尤克里里");
        });
        $("#bu6").click(function () {
            $("#lab").html("其他")
            $("#sel").val("其他");
        });
    });
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/ueditor/ueditor.config.js", "~/ueditor/ueditor.all.js")
    @*<script type="text/javascript">

        var nreditor = UE.getEditor('Score');
        </script>*@
    <script type="text/javascript">
        var editorOption = {
        initialFrameWidth: 930,
        initialFrameHeight: 600,
        iframeCssUrl: '/ueditor/themes/iframe.css',//样式路径
        };
        var editor = new baidu.editor.ui.Editor(editorOption);
        editor.render('Score');

    </script>
}

Guitar/Views/MusicScore/Delete.cshtml
@model Guitar.Models.MusicScore

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MusicScore</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ms_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ms_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ms_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ms_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ms_label)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ms_label)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ms_addtime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ms_addtime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users.User_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.User_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Guitar/Views/MusicScore/Details.cshtml
@model Guitar.Models.MusicScore

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}
<style>

</style>
<h2>Details</h2>

<div class="container">
    <div class="image">
        <img src="~/ueditor/net/upload/image/20180507/6366128073598594169974694.png" class="img img-responsive" />
    </div>
</div>

Guitar/Views/MusicScore/Index.cshtml
@using Guitar.Models
@using Guitar.ViewModel
@model Guitar.ViewModel.MusicDetailsViewModel
@using Webdiyer.WebControls.Mvc;

@{
    ViewBag.Title = "吉他谱";
    Layout = "~/Views/Shared/_LayoutPage3.cshtml";
}
@Styles.Render("~/bootstrap-3.3.7-dist/css/bootstrap.min.css")
@Scripts.Render("~/bootstrap-3.3.7-dist/js/bootstrap.min.js")
@Styles.Render("~/font-awesome-4.7.0/css/font-awesome.min.css")
@Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
@Scripts.Render("~/Scripts/lanrenzhijia.js")
@Styles.Render("~/Content/lanrenzhijia.css")
<script src="/demos/googlegg.js"></script>
<script src="~/Scripts/demo.js"></script>
<link href="~/Content/demo.css" rel="stylesheet" />
<link href="~/Content/port.css" rel="stylesheet" />
<link href="~/Content/One.css" rel="stylesheet" />
<script src="~/Scripts/One.js"></script>
<style>
        /* 所有class为menu的div中的ul样式 */
        .menu{
           height:30px;
           margin-top:10px;
        }
div.menu ul
{
    list-style:none; /* 去掉ul前面的符号 */
    margin: 0px; /* 与外界元素的距离为0 */
    padding: 0px; /* 与内部元素的距离为0 */
    width: auto; /* 宽度根据元素内容调整 */
}
/* 所有class为menu的div中的ul中的li样式 */
div.menu ul li
{
    float:left; /* 向左漂移，将竖排变为横排 */
}
div.menu ul li a, div.menu ul li a:visited
{
    cursor:pointer;
    /*background-color: #465c71; /* 背景色 */*/
    /*border: 1px #4e667d solid; /* 边框 */*/
    color: #dde4ec; /* 文字颜色 */
    display: block; /* 此元素将显示为块级元素，此元素前后会带有换行符 */
    line-height: 1.35em; /* 行高 */
    padding: 4px 4px; /* 内部填充的距离 */
    text-decoration: none; /* 不显示超链接下划线 */
    white-space: nowrap; /* 对于文本内的空白处，不会换行，文本会在在同一行上继续，直到遇到 <br> 标签为止。 */
}
div.menu ul li a:hover
{
    background-color: #bfcbd6; /* 背景色 */
    color: #465c71; /* 文字颜色 */
    text-decoration: none; /* 不显示超链接下划线 */
}
div.menu ul li a:active
{
    background-color: #465c71; /* 背景色 */
    color: #cfdbe6; /* 文字颜色 */
    text-decoration: none; /* 不显示超链接下划线 */
}
.yiren{
    width:100%;
    padding:0;
    margin:0;
}
.yuepu{
    padding-top:30px;
    width:100%;
}
</style>
<div class="">
    <div class="menu">
        <ul style="">
            <li><a href="@Url.Action("Index","Home")">首页</a></li>
            <li><a>></a></li>
            <li><a style="color:#000000">吉他谱</a></li>
        </ul>
    </div>
    <div class="yiren">
        <h3 style="">热门谱集</h3>
        <div class="row">
            @foreach (Users m in Model.Us2)
            {
                <div class="col-sm-6 col-md-2">
                    <div class="thumbnail">
                     <a href="@Url.Action("Index","Users",new { id=@m.User_id})"><img src="@m.User_img" alt="" width="171" height="171"></a> 
                        <div class="caption">
                            <p>@m.User_name</p>
                        </div>
                    </div>
                </div>
            }
            
        </div>
    </div>
   
    <div class="yuepu">
        <div class="lanrenzhijia">
            <div class="title cf">
                <a class="f1" style="text-decoration:none;display:inline;font-size:25px;cursor:pointer;color:#000000">分类</a>
                <ul class="title-list fr cf ">
                    <li class="on">民谣吉他</li>
                    <li>古典吉他</li>
                    <li>电吉他</li>
                    <li>尤克里里</li>
                    <li>其他</li>
                    <p><b></b></p>
                </ul>
            </div>
            <div class="product-wrap">

                <div class="product showw">

                    <ul class="cf">
                        @foreach (MusicScore p in Model.MScore1)
                        {
                            <li>
                                <a href="@Url.Action("Display","MusicScore", new { id = @p.Ms_id,name=@p.Ms_title})" class="imgwrap"> <img class="img-responsive" src="@p.Ms_img"> </a>
                                <p class="mt10"> <a href="">@p.Ms_title</a></p>
                                <p class="pb10"> @p.Ms_label</p>
                            </li>  }
                    </ul>

                </div>
                <!--案例2-->
                <div class="product">
                    <ul class="cf">
                        @foreach (MusicScore p in Model.MScore2)
                        {
                            <li>
                                <a href="@Url.Action("Display","MusicScore", new { id = @p.Ms_id,name=@p.Ms_title})" class="imgwrap"> <img class="img-responsive" src="@p.Ms_img"> </a>
                                <p class="mt10"> <a href="">@p.Ms_title</a></p>
                                <p class="pb10"> @p.Ms_label</p>
                            </li>  }
                    </ul>
                </div>
                <!--案例3-->
                <div class="product">
                    <ul class="cf">
                        @foreach (MusicScore p in Model.MScore3)
                        {
                            <li>
                                <a href="@Url.Action("Display","MusicScore", new { id = @p.Ms_id,name=@p.Ms_title})" class="imgwrap"> <img class="img-responsive" src="@p.Ms_img"> </a>
                                <p class="mt10"> <a href="">@p.Ms_title</a></p>
                                <p class="pb10"> @p.Ms_label</p>
                            </li>  }
                    </ul>
                </div>
                <div class="product">
                    <ul class="cf">
                        @foreach (MusicScore p in Model.MScore4)
                        {
                            <li>
                                <a href="@Url.Action("Display","MusicScore", new { id = @p.Ms_id,name=@p.Ms_title})" class="imgwrap"> <img class="img-responsive" src="@p.Ms_img"> </a>
                                <p class="mt10"> <a href="">@p.Ms_title</a></p>
                                <p class="pb10"> @p.Ms_label</p>
                            </li>  }
                    </ul>
                </div>
                <div class="product">
                    <ul class="cf">
                        @foreach (MusicScore p in Model.MScore5)
                        {
                            <li>
                                <a href="@Url.Action("Display","MusicScore", new { id = @p.Ms_id,name=@p.Ms_title})" class="imgwrap"> <img class="img-responsive" src="@p.Ms_img"> </a>
                                <p class="mt10"> <a href="">@p.Ms_title</a></p>
                                <p class="pb10"> @p.Ms_label</p>
                            </li>  }
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="yiren">
        <h3>热门吉他谱</h3>
        <div id="mscore">
            @Html.Partial("_Index1", Model.MScore6)
        </div>
        @section scripts{@{Html.RegisterMvcPagerScriptResource();}}
        
        @*<div class="wrapper">
            <ul>
                @foreach (MusicScore m in Model.MScore6)
                {
                    <li>
                        <div class='picBox'>
                            <div class='showww'>
                                <image height='180px' width='180px' src='@m.Ms_img'></image>
                            </div>
                            <div class='hidee'>
                                <h3>
                                    @m.Ms_title
                                </h3>
                            </div>
                        </div>
                    </li>
                }
               
            </ul>
            </div>*@
        </div>
    <script src="~/Scripts/demo.js"></script>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    </div>
@Scripts.Render("~/bundles/jquery")