Guitar/Controllers/LoginRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using Guitar.Models;
using System.Data.Entity.Validation;
using System.Text;
using Guitar.ViewModel;

namespace Guitar.Controllers
{
    public class LoginRegisterController : Controller
    {
        // GET: LoginRegister
        GuitarEntities db = new GuitarEntities();
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult LogOff()
        {
            Session["User_name"] = null;

            return RedirectToAction("Index", "Home");
        }
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Users user, string returnUrl)
        {
            string ValidateCode = Request.Form["txtverifcode"];
            if (ValidateCode != Session["ValidateCode"].ToString())
            {
                return Content("<script>;alert('验证码错误！');history.go(-1)</script>");
            }
            try
            {
                var users = db.Users.Where(o => o.User_email == user.User_email).FirstOrDefault();
                var user2 = db.Users.Where(o => o.User_email == user.User_email).Where(o => o.User_password == user.User_password).FirstOrDefault();
                if (users == null)
                {
                    return Content("<script>;alert('该账号不存在!');history.go(-1)</script>");
                }
                if (user2== null)
                {
                    return Content("<script>;alert('密码不正确!');history.go(-1)</script>");
                    //以下代码将权限保存到Session
                    // var current_user = db.Users.Where(o => o.UserName == user.UserName).FirstOrDefault();
                    

                }
                else
                {
                    //return Content("<script>;alert('该账号不存在!');history.go(-1)</script>");
                    HttpContext.Session["Users_id"] = users.User_id;
                    HttpContext.Session["User_name"] = users.User_name;
                    HttpContext.Session["User_email"] = users.User_email;
                    HttpContext.Session["User_img"] = users.User_img;

                    return Content("<script>;alert('登录成功!返回首页!');window.location.href='/Home/Index'</script>");
                }

                //}
                //else
                //{

                //}

                //return RedirectToAction("Login", "Login");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }


        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(Users userInfo, HttpPostedFileBase file)
        {
            string checkPwd = Request.Form["ChkUserPwd"];
            string vCode = Request.Form["txtverifcode1"];

            if (string.IsNullOrEmpty(checkPwd))
            {
                ModelState.AddModelError("ChkUserPwd", "确认密码不能为空");
            }
            else
            {
                if ((checkPwd) != (userInfo.User_password).ToString())
                {
                    ModelState.AddModelError("PwdRepeatError", "确认密码不正确");
                }
            }
            if (vCode != Session["ValidateCode"].ToString())
            {
                return Content("<script>;alert('验证码错误！');history.go(-1)</script>");
            }
            var user1 = from m in db.Users
                        select new UserViewModel
                        {
                            User_id = m.User_id,
                            User_email = m.User_email,
                            User_name = m.User_name,
                            User_password = m.User_password,
                            User_img = m.User_img,
                        };
            var isUserExists = user1.Where(a => a.User_name == userInfo.User_name).FirstOrDefault();
            var isEmailExists = user1.Where(a => a.User_email == userInfo.User_email).FirstOrDefault();

            if (isUserExists != null)
                return Content("<script>;alert('用户名已被占用！');history.go(-1)</script>");
            if (isEmailExists != null)
                return Content("<script>;alert('邮箱已被注册！');history.go(-1)</script>");
            userInfo.User_addtime = DateTime.Now;
            userInfo.User_password = userInfo.User_password;
            userInfo.User_img = "/Images/headimg/head.jpg";
            try
            {
                db.Users.Add(userInfo);
                db.SaveChanges();
                HttpContext.Session["Users_id"] = userInfo.User_id;
                HttpContext.Session["User_name"] = userInfo.User_name;
                HttpContext.Session["User_email"] = userInfo.User_email;
                HttpContext.Session["User_img"] = userInfo.User_img;
                return Content("<script>;alert('注册成功!正在跳转到首页..');window.location.href='/Home/Index'</script>");
            }
            catch (DbEntityValidationException dbEx)
            {
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Trace.TraceInformation("Property: {0} Error: {1}",
                        validationError.PropertyName,
                        validationError.ErrorMessage);
                    }
                }
                throw;
            }
        }
    }
}

Guitar/Views/LoginRegister/Login.cshtml
@model Guitar.Models.Users
@{
    ViewBag.Title = "登录";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
@{
    Html.EnableClientValidation();
}
@Styles.Render("~/Content/Login.css")
@Scripts.Render("~/Scripts/Register.js")

@Scripts.Render("~/Scripts/jquery-3.3.1.js")
@Scripts.Render("~/Scripts/jquery.validate.js")
<script src="~/Scripts/jquery.validate.js"></script>
<style>
    .content {
        margin: 30px 0;
    }

    .login {
        
        margin: 30px;
        height: 300px;
    }
    .loginimg{
        margin:30px 0px;
        width:100px;
        height:100px;
    }
</style>
<script>
    $(function () {

        // 为看不清楚绑定事件
        $("#see").click(function () {
            $("#validimg").attr("src", "@Url.Content("~/YZM/GetYZM?")" + Math.random());
        });

        // 为验证码绑定click与mouseover
        $("#validimg").mouseover(function () {
            $(this).css("cursor", "pointer");
        }).click(function () {
            $("#see").trigger("click");
        });
    });
    function reloadcode() {
        var verify = document.getElementById('validimg');
        verify.setAttribute('src', '@Url.Content("/YZM/GetYZM?")' + Math.random());
    }

    function reloadcodes() {
        var verify = document.getElementById('validimgs');
        verify.setAttribute('src', '@Url.Content("/YZM/GetYZM?")' + Math.random());
    }

</script>
<div class="container">

<div class="loginimg"><img src="~/Images/登录.png" class="img-responsive" /></div>
 <div class="login">
    @using (Html.BeginForm("Login", "LoginRegister", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "addForm" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">邮箱号</label>
            <div class="col-sm-6">
                @Html.TextBoxFor(model => model.User_email, new { @class = "form-control", type = "text", id = "phonum", style = "width: 300px;" })
                @Html.ValidationMessageFor(model => model.User_email)
            </div>
        </div>

        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
            <div class="col-sm-6">
                @Html.TextBoxFor(model => model.User_password, new { @class = "form-control", placeholder = "Password", type = "password", id = "txtpassword", style = "width: 300px;" })
                @*<input type="password" style="width: 300px;" class="form-control" id="" placeholder="Password">*@
                @Html.ValidationMessageFor(model => model.User_password)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">验证码</label>
            <div class="col-sm-6">
                <div style="float: left;">
                    <input style="width: 200px;" class="form-control" id="txtverifcode" name="txtverifcode" type="text">
                    @*<input id="txtverifcode" name="txtverifcode" class="login_verifcode" placeholder="验证码" type="text" />*@
                    @*<span id="codenameTip">*@

                </div>
                <div style="float: left;">
                    <span id="txtverifcod"><img id="validimg" src="@Url.Action("GetYZM", "YZM")" alt="看不清，点击换一张" /><a style="text-decoration:none;cursor:pointer" id="see" onclick="reloadcode()">换一张</a></span>
                    <span>@ViewBag.mess</span>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                @*@Html.CheckBoxFor(model => model)*@
                @Html.RadioButtonFor(model => model.User_password, true, new { @id = "radio1", @name = "Status",  })
                <label for="radio1">记住我</label>
                @*<span>记住我</span>*@
                <span style="padding-left:155px"><a style="text-decoration:none">忘记密码?</a></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                @*<button type="button" id="btnlogin" class="btn btn-primary">立即登录</button>*@
                <input type="submit" id="btnlogin" class="btn btn-info" value="立即登录" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <a style="text-decoration:none;" href="@Url.Action("Register","LoginRegister")">还没账号?立即注册</a> 
            </div>
        </div>
    }

</div>
    </div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Guitar/Views/LoginRegister/Register.cshtml
@model Guitar.ViewModel.UserViewModel
@using Guitar.ViewModel
@{
    ViewBag.Title = "注册";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@{
    Html.EnableClientValidation();
}
@Styles.Render("~/Content/Login.css")
@Scripts.Render("~/Scripts/Register.js")

@Scripts.Render("~/Scripts/jquery-3.3.1.js")
@Scripts.Render("~/Scripts/jquery.validate.js")
<script src="~/Scripts/jquery.validate.js"></script>
<style>
    .content {
        margin: 30px 0;
    }

    .login {
        margin: 30px;
        height: 300px;
    }

    .loginimg {
        margin: 30px 0px;
        width: 100px;
        height: 100px;
    }

    .valid {
        color: #ff7517;
        font-family: 'Comic Sans MS';
    }
</style>
<script>
    $(function () {
        // 为看不清楚绑定事件
        $("#see").click(function () {
            $("#validimg").attr("src", "@Url.Content("~/YZM/GetYZM?")" + Math.random());
        });
        // 为验证码绑定click与mouseover
        $("#validimg").mouseover(function () {
            $(this).css("cursor", "pointer");
        }).click(function () {
            $("#see").trigger("click");
        });
    });
    function reloadcodes() {
        var verify = document.getElementById('validimgs');
        verify.setAttribute('src', '@Url.Content("/YZM/GetYZM?")' + Math.random());
    }

</script>
<div class="container">
    <div class="loginimg"><img src="~/Images/注册.png" class="img-responsive" /></div>
    <div class="login">
        @using (Html.BeginForm("Register", "LoginRegister", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary()
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.User_name, new { @class = "form-control", id = "username", style = "width: 300px;" })
                    @Html.ValidationMessageFor(model => model.User_name, null, new { @class = "valid" })
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.User_password, new { @class = "form-control", placeholder = "Password", type = "password", id = "R_password", style = "width: 300px;" })
                    @*<input type="password" style="width: 300px;" class="form-control" id="" placeholder="Password">*@
                    @Html.ValidationMessageFor(model => model.User_password, null, new { @class = "valid" })
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">确认密码</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.ConfirmPassword, new { @class = "form-control", placeholder = "ConfirmPassword", type = "password", id = "ChkUserPwd", name = "ChkUserPwd", style = "width: 300px;" })
                    @*<input type="password" style="width: 300px;" class="form-control" id="ChkUserPwd" name="ChkUserPwd" placeholder="Password">*@
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, null, new { @class = "valid" })
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">邮箱号</label>
                <div class="col-sm-6">
                    <div style="float: left;">
                        @Html.TextBoxFor(model => model.User_email, new { @class = "form-control", type = "text", id = "phonum", style = "width: 300px;" })
                        @Html.ValidationMessageFor(model => model.User_email, null, new { @class = "valid" })
                        @*<input id="phonum" type="text" class="form-control" style="width: 300px;">*@
                    </div>
                    @*<div style="float: left;">
                            <input class="btn btn-info" type="button" id="getcode" value="点击获取邮箱验证码" />
                            <span id="telephonenameTip"></span>
                        </div>*@
                </div>
            </div>

            @*<div class="form-group">
                    <label class="col-sm-2 control-label">验证码</label>
                    <div class="col-sm-6">
                        <input style="width: 300px;" class="form-control" id="codename">
                        <span id="codenameTip"></span>
                    </div>
                </div>*@

            <div class="form-group">
                <label class="col-sm-2 control-label">验证码</label>
                <div class="col-sm-6">
                    <div style="float: left;">
                        <input style="width: 200px;" class="form-control" id="txtverifcode1" name="txtverifcode1" type="text">
                        @*<input id="txtverifcode" name="txtverifcode" class="login_verifcode" placeholder="验证码" type="text" />*@
                        @*<span id="codenameTip">*@

                    </div>
                    <div style="float: left;">
                        <span id="txtverifcod2"><img id="validimgs" src="@Url.Action("GetYZM", "YZM")" alt="看不清，点击换一张" /><a style="text-decoration:none;cursor:pointer" id="seee" onclick="reloadcodes()">换一张</a></span>
                    </div>
                </div>
            </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-6">
                            @*<button type="button" id="submit" class="btn btn-primary">立即注册</button>*@
                            <input type="submit" class="btn btn-info" value="立即注册" />
                        </div>
                    </div>
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}