Guitar/Models/Video.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guitar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.VideoCollection = new HashSet<VideoCollection>();
            this.VideoComment = new HashSet<VideoComment>();
            this.VideoReply = new HashSet<VideoReply>();
        }
    
        public int Vi_id { get; set; }
        public int User_id { get; set; }
        public string Vi_url { get; set; }
        public string Vi_title { get; set; }
        public string Vi_description { get; set; }
        public string Vi_img { get; set; }
        public string Vi_label { get; set; }
        public System.DateTime Vi_addtime { get; set; }
        public int ReadCount { get; set; }
        public int Collection { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoCollection> VideoCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoComment> VideoComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoReply> VideoReply { get; set; }
    }
}

Guitar/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Guitar.Models;
using Guitar.ViewModel;
using Webdiyer.WebControls.Mvc;
namespace Guitar.Controllers
{
    public class VideoController : Controller
    {
        private GuitarEntities db = new GuitarEntities();
        #region 视频主页
        // GET: Video
        public ActionResult Index(int id = 1, int pageIndex = 1, int page = 1)
        {
            var video = from m in db.Video
                        join n in db.Users on m.User_id equals n.User_id
                        select new VideoUserViewModel
                        {
                            Vi_id = m.Vi_id,
                            Vi_title = m.Vi_title,
                            Vi_addtime = m.Vi_addtime,
                            Vi_label = m.Vi_label,
                            Vi_img = m.Vi_img,
                            User_id = n.User_id,
                            User_name = n.User_name,
                        };
            var video1 = from m in video.OrderByDescending(p => p.Vi_addtime) select m;
            const int pageSize = 12;
            if (Request.IsAjaxRequest())
            {
                var target = Request.QueryString["target"];
                if (target == "video")
                {
                    return PartialView("_Index1", video1.ToPagedList(id, pageSize));
                }
            }
            return View(video1.ToPagedList(page, pageSize));
        }
        #endregion
        #region 视频细节
        public ActionResult Details(int? id, int md = 1, int pageIndex = 1, int page = 1)
        {
           
             if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var vid = db.Video.Find(id);
            var user = db.Users.Find(vid.User_id);
            if (vid == null && user == null)
            {
                return HttpNotFound();
            }
            var vid1 = (from m in db.Video.Where(p => p.User_id == vid.User_id).OrderByDescending(p => p.Vi_addtime) select m).Take(8);
            TempData["Vi_id2"] = id;
            TempData["Vi_idd"] = id;
            if (Session["Users_id"] != null)
            {
                var userid = Convert.ToInt32(Session["Users_id"]);
                var coll =(from m in db.VideoCollection.Where(p => p.User_id == userid).Where(p => p.Vi_id == id) select m).FirstOrDefault();
                if (coll!=null&&coll.State ==1)
                {
                    ViewBag.rel = "unlike";
                }
                else
                {
                    ViewBag.rel = "like";
                }
                var distribute =(from m in db.Friend.Where(p => p.UserA == userid) select m).FirstOrDefault();
                if(distribute!=null)
                {
                 if (distribute.UserB ==vid.User_id)
                    {
                        ViewBag.dis = "已关注";
                    }
                    else
                    {
                        
                    }
                }
                else
                {
                    ViewBag.dis = "关注";
                }
               
            }
            else
            {
                ViewBag.dis = "关注";
                ViewBag.rel = "like";
            }
            var comment = from m in db.VideoComment.Where(p => p.Vi_id == id).OrderByDescending(p => p.Addtime) select m;
            var comment1 = from m in db.VideoComment
                          join n in db.Users on m.User_id equals n.User_id
                          select new VideoCommentViewModel
                          {
                              Vi_commentid = m.Vi_commentid,
                              Vi_id = m.Vi_id,
                              content = m.content,
                              Addtime = m.Addtime,
                              User_id = n.User_id,
                              User_name = n.User_name,
                              User_img = n.User_img,
                          };
            //var comment1 = .ToPagedList(idd, pageSize);
            var vidreply = (from n in db.VideoReply
                       join m in comment1 on n.Vi_commentid equals m.Vi_commentid
                       join q in db.Users on n.User_id equals q.User_id
                       select new VideoCommentReplyViewModel
                       {
                           Vi_replyid = n.Vi_replyid,
                           Vi_commentid = m.Vi_commentid,
                           content = n.content,
                           Addtime = n.Addtime,
                           Vi_id = m.Vi_id,
                           User_id = n.User_id,
                           User_name = q.User_name,
                           User_img = q.User_img
                       });
            var vidcomment = from m in comment1.Where(p => p.Vi_id == id).OrderByDescending(p => p.Addtime) select m;
            //分页数据
            const int pageSize = 5;
            if (Request.IsAjaxRequest())
            {
                var target = Request.QueryString["target"];
                if (target == "articles")
                {
                    return PartialView("_details1", vidcomment.ToPagedList(md, pageSize));
                }
            }
            var index = new Guitar.ViewModel.VideoDetailsViewModel()
            {
                Us = user,
                Vid = vid,
                Vid1 = vid1,
                Vidcomment = vidcomment.ToPagedList(page, pageSize),
                Vidreply = vidreply,
            };
            return View(index);
        }
        #endregion
        #region 发布视频
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Video video)
        {
            var sel = Request["sel"];
            HttpPostedFileBase postimageBase = Request.Files["Image1"];
            HttpPostedFileBase postvideoBase = Request.Files["VideoFile"];
            if (ModelState.IsValid)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        if (postimageBase != null)
                        {
                            string filePath = postimageBase.FileName;
                            string filename = filePath.Substring(filePath.LastIndexOf("\\") + 1);
                            string serverpath = Server.MapPath(@"/Images/FM/") + filename;
                            string relativepath = @"/Images/FM/" + filename;
                            postimageBase.SaveAs(serverpath);
                            video.Vi_img = relativepath;
                        }

                        else
                        {
                            return Content("<script>;alert('请先上传封面！');history.go(-1)</script>");

                        }
                        if (postvideoBase != null)
                        {
                            string filePath = postvideoBase.FileName;
                            string fileName = filePath.Substring(filePath.LastIndexOf("\\") + 1);
                            string serverpath = Server.MapPath(@"/Videos/") + fileName;
                            string relativepath = @"/Videos/" + fileName;
                            postvideoBase.SaveAs(serverpath);
                            video.Vi_url = relativepath;
                        }

                        else
                        {
                            return Content("<script>;alert('视频没有上传！');history.go(-1)</script>");

                        }
                        video.User_id = Convert.ToInt32(Session["Users_id"].ToString());
                        //publish_food.Amount = 0;
                        video.Vi_addtime = System.DateTime.Now;
                        video.Vi_label = sel;
                        db.Video.Add(video);
                        db.SaveChanges();
                        //return Content("<script>;alert('分享成功!');window.location.href='/Publish_Food/Index_PF'</script>");
                        return Content("<script>;alert('发布成功!');history.go(-1)</script>");
                    }
                    else
                    {
                        return Content("<script>;alert('发布失败！');history.go(-1)</script>");
                    }
                }
                catch (Exception ex)
                {
                    return Content(ex.Message);
                }

            }
            return View();
        }
        #endregion
        #region 收藏
        [HttpPost]
        public string Collection(VideoCollection vi)
        {
            if (Session["Users_id"] != null)
            {
                int Vi_id = Convert.ToInt32(Request["vid"]);
                int User_id = Convert.ToInt32(Session["Users_id"]);
                var vi1 = db.VideoCollection.Where(o => o.User_id == User_id).Where(o => o.Vi_id == Vi_id).FirstOrDefault();
                if (vi1 == null)
                {
                    if (ModelState.IsValid)
                    {
                        vi.Vi_id = Vi_id;
                        vi.User_id = User_id;
                        vi.State = 1;
                        db.VideoCollection.Add(vi);
                        db.SaveChanges();
                        var collection = db.Video.Find(Vi_id);

                        collection.Collection = collection.Collection + 1;
                        var coll = collection.Collection;
                        db.SaveChanges();
                    //return Json("");
                    //return Content("<script>;alert('收藏成功!');</script>");
                    //return new EmptyResult();
                    return "11";
                }

Guitar/Views/Video/Create.cshtml
@model Guitar.Models.Video

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}
<script src="~/ueditor/ueditor.all.js"></script>
<script src="~/ueditor/ueditor.config.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="~/ueditor/themes/default/css/ueditor.css" rel="stylesheet" />
<script src="~/ueditor/lang/zh-cn/zh-cn.js"></script>
<link href="~/bootstrap-3.3.7-dist/css/bootstrap-fileinput.css" rel="stylesheet" />
<script src="~/bootstrap-3.3.7-dist/js/bootstrap-fileinput.js"></script>
<link href="~/Content/One.css" rel="stylesheet" />
<style>
    .fab {
        border-bottom: 2px solid #e8e8e8;
        color: #222;
        font-size: 16px;
        height: 64px;
        list-style: none;
    }

    .fabiao {
        display: inline-block;
        margin-right: 30px;
        line-height: 52px;
        cursor: pointer;
    }

        .fabiao a {
            text-decoration: none;
        }
</style>
<ul class="fab">
    <li class="fabiao"><a href="@Url.Action("Create","MusicScore")">发布吉他谱</a></li>
    <li class="fabiao"><a href="@Url.Action("Create","Video")" style="color:#090909">发表视频</a></li>
    <li class="fabiao"><a href="@Url.Action("Create","Posts")">发表帖子</a></li>
</ul>
@using (Html.BeginForm("Create", "Video", new { area = "" }, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="table-responsive" style="padding-top:15px;">
        <table class="table">
            <tbody>
                <tr>
                    <td colspan="1"><h4>视频标题</h4></td>
                    <td colspan="3">
                        @*@Html.EditorFor(model => model.Vi_title, new { htmlAttributes = new { @class = "form-control", @placeholder = "视频标题" } })*@
                        @Html.TextBoxFor(model => model.Vi_title, new { @class = "form-control", @placeholder = "视频标题" })
                        @Html.ValidationMessageFor(model => model.Vi_title, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td><h4>上传视频</h4></td>
                    <td colspan="2">
                        <input type="file" name="VideoFile" />
                        @*<span class="shangchuan">点击上传视频</span>*@
                    </td>
                </tr>
                <tr>
                    <td><h4>视频简介</h4></td>
                    <td colspan="2" >
                        @Html.TextAreaFor(model => model.Vi_description, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                </tr>
                <tr>
                    <td>
                        <h4>选择封面</h4>
                    </td>
                    <td>
                        @*<input type="file" name="Image1" />*@
                        @*@Html.EditorFor(model => model.Ms_img, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Ms_img, "", new { @class = "text-danger" })*@
                        <div class="form-group" id="uploadForm" enctype='multipart/form-data'>
                            <div class="h4">图片预览</div>
                            <div class="fileinput fileinput-new" data-provides="fileinput" id="exampleInputUpload">
                                <div class="fileinput-new thumbnail" style="width: 200px;height: auto;max-height:150px;">
                                    <img id='picImg' style="width: 100%;height: auto;max-height: 140px;" src="images/noimage.png" alt="" />
                                </div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                <div>
                                    <span class="btn btn-primary btn-file">
                                        <span class="fileinput-new">选择文件</span>
                                        <span class="fileinput-exists">换一张</span>
                                        <input type="file" name="Image1" id="Image1" accept="image/gif,image/jpeg,image/x-png">
                                    </span>
                                    <a href="javascript:;" class="btn btn-warning fileinput-exists" data-dismiss="fileinput">移除</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><h4>选择类型</h4></td>
                    <td colspan="2">

                        <div class="btn-group btn-group-lg">
                            <button id="bu2" type="button" class="btn btn-default">教学</button>
                        </div>
                        <div class="btn-group btn-group-lg">
                            <button id="bu3" type="button" class="btn btn-default">专辑</button>
                        </div>
                        <div class="btn-group btn-group-lg">
                            <button id="bu4" type="button" class="btn btn-default">评测</button>
                        </div>
                        <br />
                        <br />
                        <a style="color:black;text-decoration:none;">你的选择:</a><label for="lab" id="lab"></label><input type="hidden" name="sel" id="sel" />
                        <br />
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <input type="submit" value="发布" class="btn btn-info btn-lg" />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
}


<script>
    $(document).ready(function () {

        $("#bu2").click(function () {
            $("#lab").html("教学");
            $("#sel").val("教学");
            //$.post("/Posts/Create", { frontViewData: data }, function () {
            //    //alert("submit data is OK!");
            //});
            //location.href = "/home/getvalue?method=querystring";
        });
        $("#bu3").click(function () {
            $("#lab").html("专辑");
            $("#sel").val("专辑");
        });

        $("#bu4").click(function () {
            $("#lab").html("评测");
            $("#sel").val("评测");
        });

    });
</script>

Guitar/Views/Video/Delete.cshtml
@model Guitar.Models.Video

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Video</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vi_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vi_url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vi_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vi_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vi_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vi_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vi_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vi_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vi_addtime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vi_addtime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users.User_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.User_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Guitar/Views/Video/Edit.cshtml
@model Guitar.Models.Video

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Video</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Vi_id)

        <div class="form-group">
            @Html.LabelFor(model => model.User_id, "User_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("User_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.User_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vi_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vi_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vi_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vi_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vi_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vi_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vi_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vi_description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vi_description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vi_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vi_img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vi_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vi_addtime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vi_addtime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vi_addtime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Guitar/Views/Video/Index.cshtml
@using Guitar.Models
@using Guitar.ViewModel
@model Webdiyer.WebControls.Mvc.PagedList<Guitar.ViewModel.VideoUserViewModel>
@using Webdiyer.WebControls.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage3.cshtml";
}
<link href="~/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" />
<style>
    body {
        background: #f5f5f5 !important;
    }

    .video-list {
        padding-left: 0 !important;
        padding-right: 0 !important;
    }

    .videoss {
        margin-top: 30px;
    }

    .video-list .video-item {
        margin-bottom: 20px;
        display: flex;
        flex-direction: row;
        flex-wrap: nowrap;
        background: #fff;
    }

    .video-list .video-item-lt a {
        position: static;
        display: block;
        color: #333 !important;
        text-decoration: none;
    }

    .video-list .video-item-lt img {
        max-width: 100%;
        left: 0px;
        right: 0px;
        top: 0px;
        bottom: 0px;
        height:100.8px
    }

    a img {
        border: none;
    }

    .video-list .video-item-lt {
        position: relative;
        width: 180px;
        overflow: hidden;
    }

    .video-list .video-item-rb {
        flex: 1;
        padding: 5px 15px;
        overflow: hidden;
    }

        .video-list .video-item-rb:hover {
            box-shadow: 0 0 8px rgba(64,64,64,.4);
        }

    .video-list .video-item .text-title {
        line-height: 1.5;
        max-height: 3rem;
    }

    .video-list .video-item a {
        color: #333 !important;
        text-decoration: none;
    }

    .video-list .video-item .text-block {
        line-height: 1.6rem;
        overflow: hidden;
    }

    .text-block {
        display: block;
        width: 100%;
    }

    .video-list .video-item .text-block:not(:first-child) {
        margin-top: .8rem;
    }

    .video-list .video-item .text-artist {
        opacity: .7;
    }

    .video-list .video-item .text-block:not(:first-child) {
        margin-top: .8rem;
    }

    .video-list .video-item .description {
        opacity: .7;
        height: 1.5rem;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
</style>
<h2>全部</h2>
<div id="video">
    @Html.Partial("_Index1",Model)
</div>
@section scripts{@{Html.RegisterMvcPagerScriptResource();}}

Guitar/Views/Video/VidComment.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<Guitar.ViewModel.VideoCommentViewModel>

@foreach (var p in Model)
{
    <div class="pinlun">
        <table cellspacing="0" cellpadding="0">
            <tbody>
                @*<tr>@(Model.StartItemIndex + i++)</tr>*@
                <tr>
                    <td class="ta1">
                        <div class="taimg">
                            <a href="@Url.Action("Index","Users", new { id=@p.User_id })"><img src="@p.User_img" class="img-responsive img-rounded" /></a>

                        </div>
                        <div class="taname"><a href="@Url.Action("Index","Users", new { id=@p.User_id })"></a>@p.User_name</div>
                    </td>
                    <td class="ta2">
                        <div class="taa1">
                            <i class="fa fa-user-circle" aria-hidden="true"></i> 发表于  @p.Addtime
                        </div>
                        <div class="taa2">
                            @p.content
                        </div>


                        <div class="fabiao huifu aclick">
                            <div style="float:right"><a class="">回复</a></div>
                            <div style="clear:both"></div>
                        </div>
                        @{ int md = p.Vi_commentid; }
                        <div class="comment">
                            @{Html.RenderAction("VidReply", "Video", new { param1 = p.Vi_commentid });}

                            <div class="mm aclick">
                                <div style="float:right"><a class="">我也来说一句</a></div>
                                <div style="clear:both"></div>
                            </div>
                            <lable id="HFhidden" style="display: none;"></lable>
                            <div class="myreply">
                                @*@using (Html.BeginForm("Reply", "MusicScore", FormMethod.Post, new { id = "pinglung", @class = "postbox" }))*@
                                @using (Ajax.BeginForm("Reply", "Video", new AjaxOptions
                                {
                                    HttpMethod = "Post",
                                    //InsertionMode = InsertionMode.Replace,
                                    UpdateTargetId = "HFhidden",
                                    //OnComplete = "ajaxComplete2"
                                }))
                                {
                                    <div class="myimg">
                                        <img src="@Session["User_img"]" class="img-responsive img-rounded" />
                                    </div>
                                    @*<input type="hidden" name="Ms_id2" value="@Model.MScore.Ms_id" />*@
                                    <input type="hidden" name="Commentid" value="@p.Vi_commentid" />
                                    <div class="mycontent">
                                        <textarea class="textarea2" name="pingluntextarea2"></textarea>
                                        <div class="fabiao2">
                                            @*<a href="javascript:document.getElementById('pinglung').submit()" class="btn btn-info" id="huifu">回复</a>*@
                                            <input value="回复" class="btn btn-info" type="submit" id="huifu" />
                                        </div>
                                    </div>
                                }

                            </div>
                        </div>

                    </td>
                </tr>
            </tbody>
        </table>
    </div>
                                }
<script>
    function ajaxComplete2() {
        alert("回复成功！");
    }
    $("#huifu").click(function () { //提交回复
        var time = setInterval
        clearInterval(time);
        setTimeout(function () {
            var plHidden = $("#HFhidden").text();
            if (plHidden == "aa") {

                alert("回复成功！");
                location.reload(true);
            }
            else if (plHidden == "nn") {
                alert('请先登录！');
            }
            else if (plHidden == "kong") {
                alert('回复不能为空！');
            }
        }, 1000);
    });
</script>

Guitar/Views/Video/VidReply.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<Guitar.ViewModel.VideoCommentReplyViewModel>

@{ int mm = Convert.ToInt32(ViewData["mscommentid"]);}

@foreach (var m in Model)
{
    <input type="hidden" name="Commentid1" value="@m.Vi_commentid" />
        <div class="huifui1">
            <div class="hui1">
                <div class="huiimg">
                    <a><img src="@m.User_img" class="img-responsive img-rounded" /></a>
                </div>
                <div class="huiother">
                    <div class="r1"><a>@m.User_name</a>  发表于  @m.Addtime</div>
                    <div class="r2">@m.content</div>
                </div>
                <div style="clear:both"></div>
            </div>
        </div>
}

Guitar/Views/Video/_Index2.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<Guitar.ViewModel.VideoUserViewModel>
<div class="container-fluid videoss video-list">
    <div class="row">
        @foreach (var p in Model)
        {
            <div class="col-lg-6 col-md-6 col-xs-12">
                <div class="video-item">
                    <div class="video-item-lt">
                        <a href="@Url.Action("Details","Video", new { id = @p.Vi_id,})"><img src="@p.Vi_img" width="180" alt=""></a>
                    </div>
                    <div class="video-item-rb">
                        <div class="text-block text-title">
                            <a href="@Url.Action("Details","Video", new { id = @p.Vi_id,})" title="">@p.Vi_title</a>
                        </div>
                        <div class="text-block text-artist">
                            <a href="">UP主:@p.User_name</a>
                        </div>
                        <div class="text-block description">类别:@p.Vi_label</div>
                    </div>
                </div>
            </div>
        }
        
    </div>
</div>